from __future__ import annotations

from typing import Any

class ViewProxy:
    @property
    def id(self) -> str: ...
    @property
    def view_class(self) -> str: ...

class FlatGroupViewProxy:
    """Namespace-alias view over an asset's own flattened
    attributes/relations, filtered to whichever ones are tagged
    belongsToGroup: <group_name> in the schema -- see cesdm/proxy.py."""
    @property
    def id(self) -> str: ...
    @property
    def view_class(self) -> str: ...

class EntityProxy(str):
    @property
    def id(self) -> str: ...
    @property
    def entity_class(self) -> str | None: ...
    def get_attr_value(self, name: str, default: Any = ...) -> Any: ...
    def get_relations(self, name: str) -> list[str]: ...
    def get_relation(self, name: str, default: Any = ...) -> Any: ...
    def connect(self, *nodes: str) -> EntityProxy: ...
    def add_attribute(self, attribute_id: str, value: Any, *, unit: str | None = ..., provenance_ref: str | None = ...) -> EntityProxy: ...
    def add_relation(self, relation_id: str, target_entity_id: Any, **kwargs: Any) -> EntityProxy: ...

