from __future__ import annotations

from typing import Any, ClassVar, Dict, List, Literal, Optional, TypeVar, Union, overload
from pathlib import Path
from ear.entity import Entity
from ear.entity_class import EntityClass
from ear.schema_manifest import SchemaManifest
from cesdm.proxy import EntityProxy
from cesdm.generated_proxies import (
    BoilerUnitProxy,
    CHPUnitProxy,
    CarrierDomainProxy,
    CarrierProxy,
    ControllerAVRAC1AProxy,
    ControllerAVRIEEET1Proxy,
    ControllerAVRSEXSProxy,
    ControllerAVRST1AProxy,
    ControllerGOVGGOV1Proxy,
    ControllerGOVHYGOVProxy,
    ControllerGOVIEEEG1Proxy,
    ControllerPSSPSS2AProxy,
    ControllerPSSPSS2BProxy,
    ControllerPSSSTAB1Proxy,
    ConversionPortProxy,
    ConverterTypeProxy,
    DemandUnitDispatchResultProxy,
    DemandUnitProxy,
    DispatchRunRecordProxy,
    DynamicMachineModelTypeSynchronousProxy,
    DynamicRunRecordProxy,
    ElectricalBusPowerFlowResultProxy,
    ElectricalBusProxy,
    ElectrolyserUnitProxy,
    EnergySystemModelProxy,
    ExternalSupplyProxy,
    FuelCellUnitProxy,
    GasBusProxy,
    GenerationUnitDispatchResultProxy,
    GenerationUnitDynamicResultProxy,
    GenerationUnitPowerFlowResultProxy,
    GenerationUnitProxy,
    GeneratorTypeProxy,
    GenericConversionUnitProxy,
    GenericInterconnectorProxy,
    GeographicalRegionProxy,
    HVDCLinkProxy,
    HeatBusProxy,
    HeatPumpUnitProxy,
    HydraulicStorageUnitProxy,
    HydroGenerationUnitProxy,
    HydrogenBusProxy,
    MarketZoneProxy,
    NaturalResourceProxy,
    NetworkNodeDispatchResultProxy,
    PowerFlowRunRecordProxy,
    ProfileProxy,
    ShuntUnitProxy,
    SolarGenerationUnitProxy,
    StorageTypeProxy,
    StorageUnitDispatchResultProxy,
    StorageUnitProxy,
    ThermalGenerationUnitProxy,
    TimestampSeriesProxy,
    TransformerProxy,
    TransmissionElementDispatchResultProxy,
    TransmissionElementPowerFlowResultProxy,
    TransmissionLineProxy,
    TransmissionTypeProxy,
    WindGenerationUnitProxy,
)

_T = TypeVar("_T", bound=EntityProxy)

class CesdmModel:
    classes: Dict[str, EntityClass]
    entities: Dict[str, Dict[str, Entity]]
    inheritance: Dict[str, Union[str, List[str], None]]
    schema_manifest: SchemaManifest
    def add(self, cls_name: str | None = ..., id: Any = ..., *values: Any, **kwargs: Any) -> Any: ...
    def add_attribute(self, entity_id: str, attribute_id: str, *args: Any, **kwargs: Any) -> Any: ...
    @overload
    def add_entity(self, entity_class: Literal["BoilerUnit"], entity_id: str) -> BoilerUnitProxy: ...
    @overload
    def add_entity(self, entity_class: Literal["CHPUnit"], entity_id: str) -> CHPUnitProxy: ...
    @overload
    def add_entity(self, entity_class: Literal["Carrier"], entity_id: str) -> CarrierProxy: ...
    @overload
    def add_entity(self, entity_class: Literal["CarrierDomain"], entity_id: str) -> CarrierDomainProxy: ...
    @overload
    def add_entity(self, entity_class: Literal["Controller.AVR.AC1A"], entity_id: str) -> ControllerAVRAC1AProxy: ...
    @overload
    def add_entity(self, entity_class: Literal["Controller.AVR.IEEET1"], entity_id: str) -> ControllerAVRIEEET1Proxy: ...
    @overload
    def add_entity(self, entity_class: Literal["Controller.AVR.SEXS"], entity_id: str) -> ControllerAVRSEXSProxy: ...
    @overload
    def add_entity(self, entity_class: Literal["Controller.AVR.ST1A"], entity_id: str) -> ControllerAVRST1AProxy: ...
    @overload
    def add_entity(self, entity_class: Literal["Controller.GOV.GGOV1"], entity_id: str) -> ControllerGOVGGOV1Proxy: ...
    @overload
    def add_entity(self, entity_class: Literal["Controller.GOV.HYGOV"], entity_id: str) -> ControllerGOVHYGOVProxy: ...
    @overload
    def add_entity(self, entity_class: Literal["Controller.GOV.IEEEG1"], entity_id: str) -> ControllerGOVIEEEG1Proxy: ...
    @overload
    def add_entity(self, entity_class: Literal["Controller.PSS.PSS2A"], entity_id: str) -> ControllerPSSPSS2AProxy: ...
    @overload
    def add_entity(self, entity_class: Literal["Controller.PSS.PSS2B"], entity_id: str) -> ControllerPSSPSS2BProxy: ...
    @overload
    def add_entity(self, entity_class: Literal["Controller.PSS.STAB1"], entity_id: str) -> ControllerPSSSTAB1Proxy: ...
    @overload
    def add_entity(self, entity_class: Literal["ConversionPort"], entity_id: str) -> ConversionPortProxy: ...
    @overload
    def add_entity(self, entity_class: Literal["ConverterType"], entity_id: str) -> ConverterTypeProxy: ...
    @overload
    def add_entity(self, entity_class: Literal["DemandUnit"], entity_id: str) -> DemandUnitProxy: ...
    @overload
    def add_entity(self, entity_class: Literal["DemandUnit.DispatchResult"], entity_id: str) -> DemandUnitDispatchResultProxy: ...
    @overload
    def add_entity(self, entity_class: Literal["DispatchRunRecord"], entity_id: str) -> DispatchRunRecordProxy: ...
    @overload
    def add_entity(self, entity_class: Literal["DynamicMachineModelType.Synchronous"], entity_id: str) -> DynamicMachineModelTypeSynchronousProxy: ...
    @overload
    def add_entity(self, entity_class: Literal["DynamicRunRecord"], entity_id: str) -> DynamicRunRecordProxy: ...
    @overload
    def add_entity(self, entity_class: Literal["ElectricalBus"], entity_id: str) -> ElectricalBusProxy: ...
    @overload
    def add_entity(self, entity_class: Literal["ElectricalBus.PowerFlowResult"], entity_id: str) -> ElectricalBusPowerFlowResultProxy: ...
    @overload
    def add_entity(self, entity_class: Literal["ElectrolyserUnit"], entity_id: str) -> ElectrolyserUnitProxy: ...
    @overload
    def add_entity(self, entity_class: Literal["EnergySystemModel"], entity_id: str) -> EnergySystemModelProxy: ...
    @overload
    def add_entity(self, entity_class: Literal["ExternalSupply"], entity_id: str) -> ExternalSupplyProxy: ...
    @overload
    def add_entity(self, entity_class: Literal["FuelCellUnit"], entity_id: str) -> FuelCellUnitProxy: ...
    @overload
    def add_entity(self, entity_class: Literal["GasBus"], entity_id: str) -> GasBusProxy: ...
    @overload
    def add_entity(self, entity_class: Literal["GenerationUnit"], entity_id: str) -> GenerationUnitProxy: ...
    @overload
    def add_entity(self, entity_class: Literal["GenerationUnit.DispatchResult"], entity_id: str) -> GenerationUnitDispatchResultProxy: ...
    @overload
    def add_entity(self, entity_class: Literal["GenerationUnit.DynamicResult"], entity_id: str) -> GenerationUnitDynamicResultProxy: ...
    @overload
    def add_entity(self, entity_class: Literal["GenerationUnit.PowerFlowResult"], entity_id: str) -> GenerationUnitPowerFlowResultProxy: ...
    @overload
    def add_entity(self, entity_class: Literal["GeneratorType"], entity_id: str) -> GeneratorTypeProxy: ...
    @overload
    def add_entity(self, entity_class: Literal["GenericConversionUnit"], entity_id: str) -> GenericConversionUnitProxy: ...
    @overload
    def add_entity(self, entity_class: Literal["GenericInterconnector"], entity_id: str) -> GenericInterconnectorProxy: ...
    @overload
    def add_entity(self, entity_class: Literal["GeographicalRegion"], entity_id: str) -> GeographicalRegionProxy: ...
    @overload
    def add_entity(self, entity_class: Literal["HVDCLink"], entity_id: str) -> HVDCLinkProxy: ...
    @overload
    def add_entity(self, entity_class: Literal["HeatBus"], entity_id: str) -> HeatBusProxy: ...
    @overload
    def add_entity(self, entity_class: Literal["HeatPumpUnit"], entity_id: str) -> HeatPumpUnitProxy: ...
    @overload
    def add_entity(self, entity_class: Literal["HydraulicStorageUnit"], entity_id: str) -> HydraulicStorageUnitProxy: ...
    @overload
    def add_entity(self, entity_class: Literal["HydroGenerationUnit"], entity_id: str) -> HydroGenerationUnitProxy: ...
    @overload
    def add_entity(self, entity_class: Literal["HydrogenBus"], entity_id: str) -> HydrogenBusProxy: ...
    @overload
    def add_entity(self, entity_class: Literal["MarketZone"], entity_id: str) -> MarketZoneProxy: ...
    @overload
    def add_entity(self, entity_class: Literal["NaturalResource"], entity_id: str) -> NaturalResourceProxy: ...
    @overload
    def add_entity(self, entity_class: Literal["NetworkNode.DispatchResult"], entity_id: str) -> NetworkNodeDispatchResultProxy: ...
    @overload
    def add_entity(self, entity_class: Literal["PowerFlowRunRecord"], entity_id: str) -> PowerFlowRunRecordProxy: ...
    @overload
    def add_entity(self, entity_class: Literal["Profile"], entity_id: str) -> ProfileProxy: ...
    @overload
    def add_entity(self, entity_class: Literal["ShuntUnit"], entity_id: str) -> ShuntUnitProxy: ...
    @overload
    def add_entity(self, entity_class: Literal["SolarGenerationUnit"], entity_id: str) -> SolarGenerationUnitProxy: ...
    @overload
    def add_entity(self, entity_class: Literal["StorageType"], entity_id: str) -> StorageTypeProxy: ...
    @overload
    def add_entity(self, entity_class: Literal["StorageUnit"], entity_id: str) -> StorageUnitProxy: ...
    @overload
    def add_entity(self, entity_class: Literal["StorageUnit.DispatchResult"], entity_id: str) -> StorageUnitDispatchResultProxy: ...
    @overload
    def add_entity(self, entity_class: Literal["ThermalGenerationUnit"], entity_id: str) -> ThermalGenerationUnitProxy: ...
    @overload
    def add_entity(self, entity_class: Literal["TimestampSeries"], entity_id: str) -> TimestampSeriesProxy: ...
    @overload
    def add_entity(self, entity_class: Literal["Transformer"], entity_id: str) -> TransformerProxy: ...
    @overload
    def add_entity(self, entity_class: Literal["TransmissionElement.DispatchResult"], entity_id: str) -> TransmissionElementDispatchResultProxy: ...
    @overload
    def add_entity(self, entity_class: Literal["TransmissionElement.PowerFlowResult"], entity_id: str) -> TransmissionElementPowerFlowResultProxy: ...
    @overload
    def add_entity(self, entity_class: Literal["TransmissionLine"], entity_id: str) -> TransmissionLineProxy: ...
    @overload
    def add_entity(self, entity_class: Literal["TransmissionType"], entity_id: str) -> TransmissionTypeProxy: ...
    @overload
    def add_entity(self, entity_class: Literal["WindGenerationUnit"], entity_id: str) -> WindGenerationUnitProxy: ...
    @overload
    def add_entity(self, entity_class: str, entity_id: str) -> EntityProxy: ...
    def add_relation(self, entity_id: str, relation_id: str, target_entity_id: str, **kwargs: Any) -> Any: ...
    def add_relation_if_allowed(self, entity_id: str, relation_id: str, target_id: str, *, strict: bool = ...) -> Any: ...
    def attach_availability_profile(self, asset_or_view_id: str, profile_id: str, **kwargs: Any) -> ProfileProxy: ...
    def attach_demand_profile(self, asset_or_view_id: str, profile_id: str, **kwargs: Any) -> ProfileProxy: ...
    def attach_natural_inflow_profile(self, hydraulic_storage_id: str, profile_id: str, **kwargs: Any) -> ProfileProxy: ...
    def attach_profile(self, view_or_asset_id: str, relation_id: str, profile_id: str, *, timestamp_series_id: str | None = ..., create: bool = ..., profile_type: str = ..., profile_unit: str | None = ..., data_reference: str | None = ...) -> ProfileProxy: ...
    def build_class_indexes(self) -> Any: ...
    def build_inheritance_map(self, schema_dir: str | Path) -> Dict[str, List[str]]: ...
    def build_pydantic_models(self) -> Any: ...
    def class_attributes(self, class_name: str) -> List[str]: ...
    def class_defs(self) -> Any: ...
    def class_relations(self, class_name: str) -> List[str]: ...
    def connect_single_port(self, asset_id: str, node_id: str, *, view_id: str | None = ...) -> str: ...
    def connect_two_port(self, asset_id: str, from_node_id: str, to_node_id: str, *, view_id: str | None = ...) -> str: ...
    def debug_schema(self) -> Any: ...
    def ensure_carrier(self, carrier_id: str, *, name: str | None = ..., carrier_type: str | None = ..., carrier_group: str | None = ...) -> CarrierProxy: ...
    def ensure_default_library_entity(self, entity_id: str, expected_class: str | None = ...) -> bool: ...
    @overload
    def ensure_entity(self, class_name: Literal["BoilerUnit"], entity_id: str, **attributes: Any) -> BoilerUnitProxy: ...
    @overload
    def ensure_entity(self, class_name: Literal["CHPUnit"], entity_id: str, **attributes: Any) -> CHPUnitProxy: ...
    @overload
    def ensure_entity(self, class_name: Literal["Carrier"], entity_id: str, **attributes: Any) -> CarrierProxy: ...
    @overload
    def ensure_entity(self, class_name: Literal["CarrierDomain"], entity_id: str, **attributes: Any) -> CarrierDomainProxy: ...
    @overload
    def ensure_entity(self, class_name: Literal["Controller.AVR.AC1A"], entity_id: str, **attributes: Any) -> ControllerAVRAC1AProxy: ...
    @overload
    def ensure_entity(self, class_name: Literal["Controller.AVR.IEEET1"], entity_id: str, **attributes: Any) -> ControllerAVRIEEET1Proxy: ...
    @overload
    def ensure_entity(self, class_name: Literal["Controller.AVR.SEXS"], entity_id: str, **attributes: Any) -> ControllerAVRSEXSProxy: ...
    @overload
    def ensure_entity(self, class_name: Literal["Controller.AVR.ST1A"], entity_id: str, **attributes: Any) -> ControllerAVRST1AProxy: ...
    @overload
    def ensure_entity(self, class_name: Literal["Controller.GOV.GGOV1"], entity_id: str, **attributes: Any) -> ControllerGOVGGOV1Proxy: ...
    @overload
    def ensure_entity(self, class_name: Literal["Controller.GOV.HYGOV"], entity_id: str, **attributes: Any) -> ControllerGOVHYGOVProxy: ...
    @overload
    def ensure_entity(self, class_name: Literal["Controller.GOV.IEEEG1"], entity_id: str, **attributes: Any) -> ControllerGOVIEEEG1Proxy: ...
    @overload
    def ensure_entity(self, class_name: Literal["Controller.PSS.PSS2A"], entity_id: str, **attributes: Any) -> ControllerPSSPSS2AProxy: ...
    @overload
    def ensure_entity(self, class_name: Literal["Controller.PSS.PSS2B"], entity_id: str, **attributes: Any) -> ControllerPSSPSS2BProxy: ...
    @overload
    def ensure_entity(self, class_name: Literal["Controller.PSS.STAB1"], entity_id: str, **attributes: Any) -> ControllerPSSSTAB1Proxy: ...
    @overload
    def ensure_entity(self, class_name: Literal["ConversionPort"], entity_id: str, **attributes: Any) -> ConversionPortProxy: ...
    @overload
    def ensure_entity(self, class_name: Literal["ConverterType"], entity_id: str, **attributes: Any) -> ConverterTypeProxy: ...
    @overload
    def ensure_entity(self, class_name: Literal["DemandUnit"], entity_id: str, **attributes: Any) -> DemandUnitProxy: ...
    @overload
    def ensure_entity(self, class_name: Literal["DemandUnit.DispatchResult"], entity_id: str, **attributes: Any) -> DemandUnitDispatchResultProxy: ...
    @overload
    def ensure_entity(self, class_name: Literal["DispatchRunRecord"], entity_id: str, **attributes: Any) -> DispatchRunRecordProxy: ...
    @overload
    def ensure_entity(self, class_name: Literal["DynamicMachineModelType.Synchronous"], entity_id: str, **attributes: Any) -> DynamicMachineModelTypeSynchronousProxy: ...
    @overload
    def ensure_entity(self, class_name: Literal["DynamicRunRecord"], entity_id: str, **attributes: Any) -> DynamicRunRecordProxy: ...
    @overload
    def ensure_entity(self, class_name: Literal["ElectricalBus"], entity_id: str, **attributes: Any) -> ElectricalBusProxy: ...
    @overload
    def ensure_entity(self, class_name: Literal["ElectricalBus.PowerFlowResult"], entity_id: str, **attributes: Any) -> ElectricalBusPowerFlowResultProxy: ...
    @overload
    def ensure_entity(self, class_name: Literal["ElectrolyserUnit"], entity_id: str, **attributes: Any) -> ElectrolyserUnitProxy: ...
    @overload
    def ensure_entity(self, class_name: Literal["EnergySystemModel"], entity_id: str, **attributes: Any) -> EnergySystemModelProxy: ...
    @overload
    def ensure_entity(self, class_name: Literal["ExternalSupply"], entity_id: str, **attributes: Any) -> ExternalSupplyProxy: ...
    @overload
    def ensure_entity(self, class_name: Literal["FuelCellUnit"], entity_id: str, **attributes: Any) -> FuelCellUnitProxy: ...
    @overload
    def ensure_entity(self, class_name: Literal["GasBus"], entity_id: str, **attributes: Any) -> GasBusProxy: ...
    @overload
    def ensure_entity(self, class_name: Literal["GenerationUnit"], entity_id: str, **attributes: Any) -> GenerationUnitProxy: ...
    @overload
    def ensure_entity(self, class_name: Literal["GenerationUnit.DispatchResult"], entity_id: str, **attributes: Any) -> GenerationUnitDispatchResultProxy: ...
    @overload
    def ensure_entity(self, class_name: Literal["GenerationUnit.DynamicResult"], entity_id: str, **attributes: Any) -> GenerationUnitDynamicResultProxy: ...
    @overload
    def ensure_entity(self, class_name: Literal["GenerationUnit.PowerFlowResult"], entity_id: str, **attributes: Any) -> GenerationUnitPowerFlowResultProxy: ...
    @overload
    def ensure_entity(self, class_name: Literal["GeneratorType"], entity_id: str, **attributes: Any) -> GeneratorTypeProxy: ...
    @overload
    def ensure_entity(self, class_name: Literal["GenericConversionUnit"], entity_id: str, **attributes: Any) -> GenericConversionUnitProxy: ...
    @overload
    def ensure_entity(self, class_name: Literal["GenericInterconnector"], entity_id: str, **attributes: Any) -> GenericInterconnectorProxy: ...
    @overload
    def ensure_entity(self, class_name: Literal["GeographicalRegion"], entity_id: str, **attributes: Any) -> GeographicalRegionProxy: ...
    @overload
    def ensure_entity(self, class_name: Literal["HVDCLink"], entity_id: str, **attributes: Any) -> HVDCLinkProxy: ...
    @overload
    def ensure_entity(self, class_name: Literal["HeatBus"], entity_id: str, **attributes: Any) -> HeatBusProxy: ...
    @overload
    def ensure_entity(self, class_name: Literal["HeatPumpUnit"], entity_id: str, **attributes: Any) -> HeatPumpUnitProxy: ...
    @overload
    def ensure_entity(self, class_name: Literal["HydraulicStorageUnit"], entity_id: str, **attributes: Any) -> HydraulicStorageUnitProxy: ...
    @overload
    def ensure_entity(self, class_name: Literal["HydroGenerationUnit"], entity_id: str, **attributes: Any) -> HydroGenerationUnitProxy: ...
    @overload
    def ensure_entity(self, class_name: Literal["HydrogenBus"], entity_id: str, **attributes: Any) -> HydrogenBusProxy: ...
    @overload
    def ensure_entity(self, class_name: Literal["MarketZone"], entity_id: str, **attributes: Any) -> MarketZoneProxy: ...
    @overload
    def ensure_entity(self, class_name: Literal["NaturalResource"], entity_id: str, **attributes: Any) -> NaturalResourceProxy: ...
    @overload
    def ensure_entity(self, class_name: Literal["NetworkNode.DispatchResult"], entity_id: str, **attributes: Any) -> NetworkNodeDispatchResultProxy: ...
    @overload
    def ensure_entity(self, class_name: Literal["PowerFlowRunRecord"], entity_id: str, **attributes: Any) -> PowerFlowRunRecordProxy: ...
    @overload
    def ensure_entity(self, class_name: Literal["Profile"], entity_id: str, **attributes: Any) -> ProfileProxy: ...
    @overload
    def ensure_entity(self, class_name: Literal["ShuntUnit"], entity_id: str, **attributes: Any) -> ShuntUnitProxy: ...
    @overload
    def ensure_entity(self, class_name: Literal["SolarGenerationUnit"], entity_id: str, **attributes: Any) -> SolarGenerationUnitProxy: ...
    @overload
    def ensure_entity(self, class_name: Literal["StorageType"], entity_id: str, **attributes: Any) -> StorageTypeProxy: ...
    @overload
    def ensure_entity(self, class_name: Literal["StorageUnit"], entity_id: str, **attributes: Any) -> StorageUnitProxy: ...
    @overload
    def ensure_entity(self, class_name: Literal["StorageUnit.DispatchResult"], entity_id: str, **attributes: Any) -> StorageUnitDispatchResultProxy: ...
    @overload
    def ensure_entity(self, class_name: Literal["ThermalGenerationUnit"], entity_id: str, **attributes: Any) -> ThermalGenerationUnitProxy: ...
    @overload
    def ensure_entity(self, class_name: Literal["TimestampSeries"], entity_id: str, **attributes: Any) -> TimestampSeriesProxy: ...
    @overload
    def ensure_entity(self, class_name: Literal["Transformer"], entity_id: str, **attributes: Any) -> TransformerProxy: ...
    @overload
    def ensure_entity(self, class_name: Literal["TransmissionElement.DispatchResult"], entity_id: str, **attributes: Any) -> TransmissionElementDispatchResultProxy: ...
    @overload
    def ensure_entity(self, class_name: Literal["TransmissionElement.PowerFlowResult"], entity_id: str, **attributes: Any) -> TransmissionElementPowerFlowResultProxy: ...
    @overload
    def ensure_entity(self, class_name: Literal["TransmissionLine"], entity_id: str, **attributes: Any) -> TransmissionLineProxy: ...
    @overload
    def ensure_entity(self, class_name: Literal["TransmissionType"], entity_id: str, **attributes: Any) -> TransmissionTypeProxy: ...
    @overload
    def ensure_entity(self, class_name: Literal["WindGenerationUnit"], entity_id: str, **attributes: Any) -> WindGenerationUnitProxy: ...
    @overload
    def ensure_entity(self, class_name: str, entity_id: str, **attributes: Any) -> EntityProxy: ...
    def ensure_resource(self, resource_id: str, *, name: str | None = ..., resource_type: str | None = ..., resource_group: str | None = ..., unit: str | None = ...) -> NaturalResourceProxy: ...
    def ensure_technology(self, technology_id: str, *, class_name: str = ..., name: str | None = ..., **attributes: Any) -> GeneratorTypeProxy: ...
    def entity_class(self, entity_id: str) -> Optional[str]: ...
    def entity_data(self, entity_id: str) -> Dict[str, Any]: ...
    def export_csv_by_class(self, dir_path: Union[str, pathlib.Path], include_placeholders: bool = ...) -> Any: ...
    def export_csv_by_class_wide(self, dir_path: Union[str, pathlib.Path], include_placeholders: bool = ..., include_ref_meta: bool = ...) -> Any: ...
    def export_csv_by_class_wide_meta(self, dir_path: str, include_placeholders: bool = ...) -> Any: ...
    def export_csv_by_class_wide_with_schema(self, dir_path: Union[str, pathlib.Path], include_placeholders: bool = ...) -> Any: ...
    def export_csv_by_class_with_schema(self, dir_path: Union[str, pathlib.Path], include_placeholders: bool = ...) -> Any: ...
    def export_csv_hierarchical(self, dir_path: Union[str, pathlib.Path], *, wide: bool = ..., long: bool = ...) -> None: ...
    def export_datapackage(self, dir_path: Any) -> Any: ...
    def export_excel(self, path: Union[str, pathlib.Path], *, include_non_assets: bool = ...) -> None: ...
    def export_excel_flat(self, path: Union[str, pathlib.Path], *, include_non_assets: bool = ...) -> None: ...
    def export_frictionless(self, dir_path: Union[str, pathlib.Path], *, name: str = ..., title: Optional[str] = ..., description: str = ..., version: str = ..., contributors: Optional[list] = ..., include_library: str = ...) -> pathlib.Path: ...
    def export_hdf5(self, path: Union[str, pathlib.Path], *, values_map: Optional[Dict[str, 'np.ndarray']] = ...) -> None: ...
    def export_json(self, path: str | pathlib.Path, *, include_library: IncludeLibrary = ...) -> Any: ...
    def export_json_schema(self, path: Union[str, pathlib.Path]) -> Any: ...
    def export_long_csv(self, path: str | pathlib.Path) -> Any: ...
    def export_long_csv_with_schema(self, path: Union[str, pathlib.Path]) -> Any: ...
    def export_parquet(self, path: Union[str, pathlib.Path], *, values_map: Optional[Dict[str, 'np.ndarray']] = ..., wide: bool = ...) -> None: ...
    def export_rdf_schema(self, path: Union[str, pathlib.Path], namespace: Optional[str] = ...) -> None: ...
    def export_yaml(self, path: str | pathlib.Path, *, include_library: IncludeLibrary = ...) -> Any: ...
    def export_yaml_hierarchical(self, path: str | pathlib.Path, *, include_library: str = ...) -> None: ...
    def export_yaml_model(self, path: str | pathlib.Path) -> None: ...
    def field_allowed(self, entity_or_class: str, field_id: str) -> bool: ...
    def format_attribute_tree(self, groups: Dict[str, List]) -> Any: ...
    def format_class_tree(self) -> str: ...
    def get_attr_value(self, entity_class: str, entity_id: str, attribute_id: str, default: Any = ...) -> Any: ...
    def get_attribute_value(self, entity_id: str, attribute_id: str, default: Any = ...) -> Any: ...
    def get_attributes_grouped(self, class_name: str) -> Dict[str, List[AttributeDef]]: ...
    def get_effective_attribute_value(self, view_id: str, attribute_id: str, default: Any = ..., technology_relation: str = ...) -> Any: ...
    def get_entities(self, entity_class: str) -> Dict[str, 'Entity']: ...
    def get_entity(self, entity_id: str) -> EntityProxy: ...
    def get_entity_as(self, entity_id: str, cls: type[_T] | tuple[type[_T], ...]) -> _T: ...
    def get_relation_targets(self, entity_id: str, relation_id: str) -> Any: ...
    def has_entity(self, entity_id: str) -> bool: ...
    def hydro_units_for_reservoir(self, reservoir_id: str) -> list[str]: ...
    def import_csv_by_class(self, dir_path: Union[str, pathlib.Path], create_missing_refs: bool = ...) -> Any: ...
    def import_csv_by_class_wide(self, dir_path: Union[str, pathlib.Path], *, skip_unknown_classes: bool = ..., skip_unknown_fields: bool = ...) -> Dict[str, int]: ...
    def import_csv_by_class_wide_meta(self, dir_path: str | pathlib.Path, create_missing_refs: bool = ..., strict_unknown: bool = ...) -> Any: ...
    def import_csv_hierarchical(self, dir_path: Union[str, pathlib.Path], *, create_missing_refs: bool = ..., strict_unknown: bool = ...) -> Dict[str, Any]: ...
    def import_datapackage(self, dir_path: Union[str, pathlib.Path], *, skip_unknown_classes: bool = ..., skip_unknown_fields: bool = ...) -> Dict[str, int]: ...
    def import_excel(self, path: Union[str, pathlib.Path], *, strict_unknown: bool = ...) -> Dict[str, Any]: ...
    def import_excel_flat(self, path: Union[str, pathlib.Path], *, skip_unknown_classes: bool = ..., skip_unknown_fields: bool = ...) -> Dict[str, int]: ...
    def import_frictionless(self, dir_path: Union[str, pathlib.Path], *, skip_unknown_classes: bool = ..., skip_unknown_fields: bool = ...) -> Dict[str, int]: ...
    def import_hdf5(self, path: Union[str, pathlib.Path], *, load_values: bool = ..., strict_unknown: bool = ...) -> Dict[str, Any]: ...
    def import_json(self, path: str | pathlib.Path, *, strict_unknown: bool = ...) -> Any: ...
    def import_library(self, library_yaml: str, *, namespace: str | None = ...) -> int: ...
    def import_long_csv(self, path: str | pathlib.Path, *, strict_unknown: bool = ...) -> Any: ...
    def import_parquet(self, path: Union[str, pathlib.Path], *, load_values: bool = ..., wide: bool = ...) -> Dict[str, Any]: ...
    def import_yaml(self, path: str | pathlib.Path, *, strict_unknown: bool = ...) -> Any: ...
    def import_yaml_hierarchical(self, path: str, *, strict_unknown: bool = ...) -> Any: ...
    def import_yaml_model(self, path: str | pathlib.Path, *, strict_unknown: bool = ...) -> Any: ...
    def is_class_derived_from(self, subclass_name: str, parent_name: str, inheritance: Dict[str, Union[str, List[str], None]]) -> bool: ...
    def load_analysis_profile(self, path: Union[str, Path]) -> Dict[str, Any]: ...
    def load_classes_from_yaml(self, path: Union[str, pathlib.Path, Sequence[Union[str, pathlib.Path]]]) -> Any: ...
    def obj_is_instance_of(obj: dict, parent_name: str, inheritance: dict[str, str | None], class_key: str = ...) -> bool: ...
    def print_attribute_tree(self, groups: Dict[str, List]) -> Any: ...
    def print_class_tree(self) -> Any: ...
    def reservoir_for_hydro(self, hydro_id: str) -> str | None: ...
    def resolve_inheritance(self) -> Any: ...
    def set_attr_value(self, entity_id: str, attr: str, value: Any) -> Any: ...
    def set_attribute_if_allowed(self, entity_id: str, attribute_id: str, value: Any, unit: str | None = ..., *, strict: bool = ...) -> Any: ...
    def set_technology(self, asset_id: str, technology_id: str, *, technology_class: str = ..., **technology_attrs: Any) -> bool: ...
    def summary(self, *, detailed: bool = ..., as_dict: bool = ...) -> Any: ...
    def total_capacity(self, *, asset_class: str | None = ..., region_id: str | None = ...) -> float: ...
    def unit_info(self, symbol: str) -> Any: ...
    def validate(self) -> Any: ...
    def validate_for_analysis(self, profile: Union[str, Path, Dict[str, Any]]) -> List[str]: ...
    def validate_for_analysis_or_raise(self, profile: Union[str, Path, Dict[str, Any]]) -> None: ...
    def validate_or_raise(self) -> None: ...
    def validate_relation_targets(self) -> list: ...
    def views_for_asset(self, asset_id: str) -> Dict[str, str]: ...
